# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Projects\PROGRAMMING\Repos\ShaderCreator\ui\ShaderCreator.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(374, 271)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setMaximumSize(QtCore.QSize(370, 60))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.widget_2)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lEdit_name = QtWidgets.QLineEdit(self.widget)
        self.lEdit_name.setMinimumSize(QtCore.QSize(150, 0))
        self.lEdit_name.setInputMask("")
        self.lEdit_name.setText("")
        self.lEdit_name.setObjectName("lEdit_name")
        self.verticalLayout.addWidget(self.lEdit_name)
        self.cbox_shader = QtWidgets.QComboBox(self.widget)
        self.cbox_shader.setObjectName("cbox_shader")
        self.verticalLayout.addWidget(self.cbox_shader)
        self.horizontalLayout.addWidget(self.widget)
        self.widget_12 = QtWidgets.QWidget(self.widget_2)
        self.widget_12.setObjectName("widget_12")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_12)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_create = QtWidgets.QPushButton(self.widget_12)
        self.btn_create.setMinimumSize(QtCore.QSize(100, 0))
        self.btn_create.setObjectName("btn_create")
        self.verticalLayout_4.addWidget(self.btn_create)
        self.chbox_assign = QtWidgets.QCheckBox(self.widget_12)
        self.chbox_assign.setObjectName("chbox_assign")
        self.verticalLayout_4.addWidget(self.chbox_assign)
        self.horizontalLayout.addWidget(self.widget_12)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(Form)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.chbox_diffuse = QtWidgets.QCheckBox(self.widget_4)
        self.chbox_diffuse.setMinimumSize(QtCore.QSize(90, 0))
        self.chbox_diffuse.setObjectName("chbox_diffuse")
        self.horizontalLayout_2.addWidget(self.chbox_diffuse)
        self.lEdit_diffuse = QtWidgets.QLineEdit(self.widget_4)
        self.lEdit_diffuse.setEnabled(False)
        self.lEdit_diffuse.setObjectName("lEdit_diffuse")
        self.horizontalLayout_2.addWidget(self.lEdit_diffuse)
        self.btn_diffuse = QtWidgets.QPushButton(self.widget_4)
        self.btn_diffuse.setEnabled(False)
        self.btn_diffuse.setObjectName("btn_diffuse")
        self.horizontalLayout_2.addWidget(self.btn_diffuse)
        self.verticalLayout_3.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.widget_3)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.chbox_specular = QtWidgets.QCheckBox(self.widget_5)
        self.chbox_specular.setMinimumSize(QtCore.QSize(90, 0))
        self.chbox_specular.setObjectName("chbox_specular")
        self.horizontalLayout_3.addWidget(self.chbox_specular)
        self.lEdit_specular = QtWidgets.QLineEdit(self.widget_5)
        self.lEdit_specular.setEnabled(False)
        self.lEdit_specular.setObjectName("lEdit_specular")
        self.horizontalLayout_3.addWidget(self.lEdit_specular)
        self.btn_specular = QtWidgets.QPushButton(self.widget_5)
        self.btn_specular.setEnabled(False)
        self.btn_specular.setObjectName("btn_specular")
        self.horizontalLayout_3.addWidget(self.btn_specular)
        self.verticalLayout_3.addWidget(self.widget_5)
        self.widget_6 = QtWidgets.QWidget(self.widget_3)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.chbox_roughness = QtWidgets.QCheckBox(self.widget_6)
        self.chbox_roughness.setMinimumSize(QtCore.QSize(90, 0))
        self.chbox_roughness.setObjectName("chbox_roughness")
        self.horizontalLayout_4.addWidget(self.chbox_roughness)
        self.lEdit_roughness = QtWidgets.QLineEdit(self.widget_6)
        self.lEdit_roughness.setEnabled(False)
        self.lEdit_roughness.setObjectName("lEdit_roughness")
        self.horizontalLayout_4.addWidget(self.lEdit_roughness)
        self.btn_roughness = QtWidgets.QPushButton(self.widget_6)
        self.btn_roughness.setEnabled(False)
        self.btn_roughness.setObjectName("btn_roughness")
        self.horizontalLayout_4.addWidget(self.btn_roughness)
        self.verticalLayout_3.addWidget(self.widget_6)
        self.widget_7 = QtWidgets.QWidget(self.widget_3)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.chbox_transmission = QtWidgets.QCheckBox(self.widget_7)
        self.chbox_transmission.setMinimumSize(QtCore.QSize(90, 0))
        self.chbox_transmission.setObjectName("chbox_transmission")
        self.horizontalLayout_5.addWidget(self.chbox_transmission)
        self.lEdit_transmission = QtWidgets.QLineEdit(self.widget_7)
        self.lEdit_transmission.setEnabled(False)
        self.lEdit_transmission.setObjectName("lEdit_transmission")
        self.horizontalLayout_5.addWidget(self.lEdit_transmission)
        self.btn_transmission = QtWidgets.QPushButton(self.widget_7)
        self.btn_transmission.setEnabled(False)
        self.btn_transmission.setObjectName("btn_transmission")
        self.horizontalLayout_5.addWidget(self.btn_transmission)
        self.verticalLayout_3.addWidget(self.widget_7)
        self.widget_8 = QtWidgets.QWidget(self.widget_3)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.chbox_sss = QtWidgets.QCheckBox(self.widget_8)
        self.chbox_sss.setMinimumSize(QtCore.QSize(90, 0))
        self.chbox_sss.setObjectName("chbox_sss")
        self.horizontalLayout_6.addWidget(self.chbox_sss)
        self.lEdit_sss = QtWidgets.QLineEdit(self.widget_8)
        self.lEdit_sss.setEnabled(False)
        self.lEdit_sss.setObjectName("lEdit_sss")
        self.horizontalLayout_6.addWidget(self.lEdit_sss)
        self.btn_sss = QtWidgets.QPushButton(self.widget_8)
        self.btn_sss.setEnabled(False)
        self.btn_sss.setObjectName("btn_sss")
        self.horizontalLayout_6.addWidget(self.btn_sss)
        self.verticalLayout_3.addWidget(self.widget_8)
        self.widget_9 = QtWidgets.QWidget(self.widget_3)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.chbox_sssColor = QtWidgets.QCheckBox(self.widget_9)
        self.chbox_sssColor.setMinimumSize(QtCore.QSize(90, 0))
        self.chbox_sssColor.setObjectName("chbox_sssColor")
        self.horizontalLayout_7.addWidget(self.chbox_sssColor)
        self.lEdit_sssColor = QtWidgets.QLineEdit(self.widget_9)
        self.lEdit_sssColor.setEnabled(False)
        self.lEdit_sssColor.setObjectName("lEdit_sssColor")
        self.horizontalLayout_7.addWidget(self.lEdit_sssColor)
        self.btn_sssColor = QtWidgets.QPushButton(self.widget_9)
        self.btn_sssColor.setEnabled(False)
        self.btn_sssColor.setObjectName("btn_sssColor")
        self.horizontalLayout_7.addWidget(self.btn_sssColor)
        self.verticalLayout_3.addWidget(self.widget_9)
        self.widget_10 = QtWidgets.QWidget(self.widget_3)
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.chbox_bump = QtWidgets.QCheckBox(self.widget_10)
        self.chbox_bump.setMinimumSize(QtCore.QSize(90, 0))
        self.chbox_bump.setObjectName("chbox_bump")
        self.horizontalLayout_8.addWidget(self.chbox_bump)
        self.lEdit_bump = QtWidgets.QLineEdit(self.widget_10)
        self.lEdit_bump.setEnabled(False)
        self.lEdit_bump.setObjectName("lEdit_bump")
        self.horizontalLayout_8.addWidget(self.lEdit_bump)
        self.btn_bump = QtWidgets.QPushButton(self.widget_10)
        self.btn_bump.setEnabled(False)
        self.btn_bump.setObjectName("btn_bump")
        self.horizontalLayout_8.addWidget(self.btn_bump)
        self.verticalLayout_3.addWidget(self.widget_10)
        self.widget_11 = QtWidgets.QWidget(self.widget_3)
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.chbox_displacement = QtWidgets.QCheckBox(self.widget_11)
        self.chbox_displacement.setMinimumSize(QtCore.QSize(90, 0))
        self.chbox_displacement.setObjectName("chbox_displacement")
        self.horizontalLayout_9.addWidget(self.chbox_displacement)
        self.lEdit_displacement = QtWidgets.QLineEdit(self.widget_11)
        self.lEdit_displacement.setEnabled(False)
        self.lEdit_displacement.setObjectName("lEdit_displacement")
        self.horizontalLayout_9.addWidget(self.lEdit_displacement)
        self.btn_displacement = QtWidgets.QPushButton(self.widget_11)
        self.btn_displacement.setEnabled(False)
        self.btn_displacement.setObjectName("btn_displacement")
        self.horizontalLayout_9.addWidget(self.btn_displacement)
        self.verticalLayout_3.addWidget(self.widget_11)
        self.verticalLayout_2.addWidget(self.widget_3)

        self.retranslateUi(Form)
        self.chbox_diffuse.clicked['bool'].connect(self.btn_diffuse.setEnabled)
        self.chbox_specular.clicked['bool'].connect(self.btn_specular.setEnabled)
        self.chbox_roughness.clicked['bool'].connect(self.btn_roughness.setEnabled)
        self.chbox_transmission.clicked['bool'].connect(self.btn_transmission.setEnabled)
        self.chbox_sss.clicked['bool'].connect(self.btn_sss.setEnabled)
        self.chbox_sssColor.clicked['bool'].connect(self.btn_sssColor.setEnabled)
        self.chbox_bump.clicked['bool'].connect(self.btn_bump.setEnabled)
        self.chbox_displacement.clicked['bool'].connect(self.btn_displacement.setEnabled)
        self.chbox_diffuse.clicked['bool'].connect(self.lEdit_diffuse.setEnabled)
        self.chbox_specular.clicked['bool'].connect(self.lEdit_specular.setEnabled)
        self.chbox_roughness.clicked['bool'].connect(self.lEdit_roughness.setEnabled)
        self.chbox_transmission.clicked['bool'].connect(self.lEdit_transmission.setEnabled)
        self.chbox_sss.clicked['bool'].connect(self.lEdit_sss.setEnabled)
        self.chbox_sssColor.clicked['bool'].connect(self.lEdit_sssColor.setEnabled)
        self.chbox_bump.clicked['bool'].connect(self.lEdit_bump.setEnabled)
        self.chbox_displacement.clicked['bool'].connect(self.lEdit_displacement.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lEdit_name.setPlaceholderText(_translate("Form", "Type Name"))
        self.btn_create.setText(_translate("Form", "Create"))
        self.chbox_assign.setText(_translate("Form", "Assign"))
        self.chbox_diffuse.setText(_translate("Form", "Diffuse"))
        self.lEdit_diffuse.setPlaceholderText(_translate("Form", "Texture Path"))
        self.btn_diffuse.setText(_translate("Form", "Browse"))
        self.chbox_specular.setText(_translate("Form", "Specular"))
        self.lEdit_specular.setPlaceholderText(_translate("Form", "Texture Path"))
        self.btn_specular.setText(_translate("Form", "Browse"))
        self.chbox_roughness.setText(_translate("Form", "Roughness"))
        self.lEdit_roughness.setPlaceholderText(_translate("Form", "Texture Path"))
        self.btn_roughness.setText(_translate("Form", "Browse"))
        self.chbox_transmission.setText(_translate("Form", "Transmission"))
        self.lEdit_transmission.setPlaceholderText(_translate("Form", "Texture Path"))
        self.btn_transmission.setText(_translate("Form", "Browse"))
        self.chbox_sss.setText(_translate("Form", "SSS"))
        self.lEdit_sss.setPlaceholderText(_translate("Form", "Texture Path"))
        self.btn_sss.setText(_translate("Form", "Browse"))
        self.chbox_sssColor.setText(_translate("Form", "SSS Color"))
        self.lEdit_sssColor.setPlaceholderText(_translate("Form", "Texture Path"))
        self.btn_sssColor.setText(_translate("Form", "Browse"))
        self.chbox_bump.setText(_translate("Form", "Bump"))
        self.lEdit_bump.setPlaceholderText(_translate("Form", "Texture Path"))
        self.btn_bump.setText(_translate("Form", "Browse"))
        self.chbox_displacement.setText(_translate("Form", "Displacement"))
        self.lEdit_displacement.setPlaceholderText(_translate("Form", "Texture Path"))
        self.btn_displacement.setText(_translate("Form", "Browse"))
